/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Panel.java to edit this template
 */
package gui;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import static gui.AdminSignIn.logger;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.InputStream;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Random;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import model.GrnItem;
import model.MySQL2;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import java.util.logging.*;

public class GrnManagement extends javax.swing.JPanel {

    private static HashMap<String, GrnItem> grnItemMap = new HashMap<>();
    static final Logger logger = SignIn.getLoggerObject();
    private String loginEmpEmail;

    public GrnManagement(String email) {
        try {

            UIManager.setLookAndFeel(new FlatMacDarkLaf());

        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        SwingUtilities.updateComponentTreeUI(this);
        this.revalidate();
        this.repaint();

        initComponents();

        generateGrnID();
        loadGrnItem();
        jRadioButton2.setSelected(true);
        jTextField8.setText("0.0");
        initializeCurrentPage();

        this.loginEmpEmail = email;
        jTextField1.setText(loginEmpEmail);
    }

    private void initializeCurrentPage() {
        logger.info("GRN Management Page accessed");
    }

    private String generateGrnID() {
        long timestamp = System.currentTimeMillis();
        long randomNum = new Random().nextInt(99999);

        String grnId = timestamp + "-" + randomNum;

        jTextField2.setText(grnId);

        return grnId;
    }

    public JTextField getjTextField3() {
        return jTextField3;
    }

    public JTextField getjTextField4() {
        return jTextField4;
    }

    public JTextField getjTextField5() {
        return jTextField5;
    }

    public JTextField getjTextField6() {
        return jTextField6;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    private void loadGrnItem() {

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        double total = 0;

        for (GrnItem grnitem : grnItemMap.values()) {
            Vector<String> vector = new Vector<>();
            vector.add(grnitem.getProductID());
            vector.add(grnitem.getProductName());
            vector.add(grnitem.getCategory());
            vector.add(String.valueOf(grnitem.getQty()));
            vector.add(String.valueOf(grnitem.getBuyingPrice()));
            vector.add(String.valueOf(grnitem.getSellingPrice()));
            vector.add(sdf.format(date));

            double itemTotal = (grnitem.getQty()) * grnitem.getBuyingPrice();

            total += itemTotal;

            vector.add(String.valueOf(itemTotal));
            vector.add(String.valueOf(grnitem.getDiscount()));
            vector.add(String.valueOf(grnitem.getDiscountStart()));
            vector.add(String.valueOf(grnitem.getDiscountEnd()));

            dtm.addRow(vector);

        }

        jFormattedTextField3.setText(String.valueOf(total));

    }

    public class CustomJasperViewer extends JasperViewer {

        public CustomJasperViewer(JasperPrint jasperPrint, boolean view) {
            super(jasperPrint, view);
            setAlwaysOnTop(true); // Ensure the window is always on top
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(950, 650));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3), "Employee Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 209, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3), "GRN No", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 75, 209, -1));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3), "Supplier Mobile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, 209, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Select");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 4, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 194, 209, 43));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3), "Product ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 16, 151, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Select");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 4, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 19, 48, 38));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3), "Product Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 75, 203, -1));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3), "Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 134, 203, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3), "Genres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 194, 203, 53));

        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3), "Buying Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 17, 228, -1));

        jFormattedTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3), "Selling Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        jFormattedTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField2KeyReleased(evt);
            }
        });
        jPanel1.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 76, 130, -1));

        jTextField7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 3), "Quantity", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 135, 228, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 255, 204));
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 3));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 76, 92, 41));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Add to GRN");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 4, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 194, 228, 43));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 4));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 0, -1, 253));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 204, 204));
        jLabel15.setText("Discount (Percentage)");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 60, -1, -1));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 88, 130, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 204));
        jLabel16.setText("Discount Availability");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 12, 125, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(153, 153, 255));
        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 34, 52, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(153, 153, 255));
        jRadioButton2.setText("No");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 34, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 204, 204));
        jLabel17.setText("Discount Start");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 122, 83, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 144, 225, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 204));
        jLabel18.setText("Discount End");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 178, 83, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 200, 225, -1));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 88, 77, 22));

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "P.Name", "Category", "QTY", "Buying Price", "Selling Price", "Date", "Total", "Discount (Stock)", "Discount Start (stock)", "Discount End (Stock)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 204, 204));
        jButton5.setText("Save GRN");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 5, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 204));
        jLabel12.setText("Total");

        jFormattedTextField3.setEditable(false);
        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField3.setText("0");

        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField4KeyReleased(evt);
            }
        });

        jFormattedTextField5.setEditable(false);
        jFormattedTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jFormattedTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jFormattedTextField5.setForeground(new java.awt.Color(153, 153, 255));
        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField5.setText("0");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 204, 204));
        jLabel13.setText("Payment");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 204));
        jLabel14.setText("Balance");

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("View GRN History");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 5, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Clear All");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 5, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(204, 204, 255));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 4));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 615, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                        .addGap(17, 17, 17))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(610, 610, 610)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(337, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(221, 221, 221)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
// private SupplierRegistration spr1;
    private JFrame supplierRegistrationFrame;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (supplierRegistrationFrame == null || !supplierRegistrationFrame.isDisplayable()) {
            supplierRegistrationFrame = new JFrame("Supplier Registration");
            supplierRegistrationFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            supplierRegistrationFrame.setSize(950, 650);
            supplierRegistrationFrame.setLocationRelativeTo(null);

            SupplierRegistration sr = new SupplierRegistration(jPanel1);

            sr.disableOrRemoveLabel();

            sr.setGrnManagement(this);

            supplierRegistrationFrame.setContentPane(sr);

            supplierRegistrationFrame.setVisible(true);

        } else {
            supplierRegistrationFrame.requestFocus();
            supplierRegistrationFrame.toFront();

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed
    private JFrame frameP;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (frameP == null || !frameP.isDisplayable()) {
            frameP = new JFrame("Product Management");
            frameP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frameP.setSize(950, 650);
            frameP.setLocationRelativeTo(null);

            ProductManagement pm = new ProductManagement();

            pm.setGrnManagement(this);

            frameP.setContentPane(pm);

            frameP.setVisible(true);
        } else {
            frameP.requestFocus();
            frameP.toFront();

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed
    Double desiredProfit;
    private void jFormattedTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField2KeyReleased
        String bp = jFormattedTextField1.getText();
        String sp = jFormattedTextField2.getText();

        desiredProfit = Double.parseDouble(bp) * 50 / 100;

        jLabel21.setText(String.valueOf(Double.parseDouble(bp) + desiredProfit));

        Double possibleDiscountPrice = Double.parseDouble(sp) - Double.parseDouble(bp) - desiredProfit;

        Double findalDiscount = (possibleDiscountPrice * 100) / Double.parseDouble(sp);
        jLabel20.setText(String.format("%.2f%%", findalDiscount));

    }//GEN-LAST:event_jFormattedTextField2KeyReleased

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String buyingPrice = jFormattedTextField1.getText();
        String sellingPrice = jFormattedTextField2.getText();
        String qty = jTextField7.getText();

        Number valueBuying = (Number) jFormattedTextField1.getValue();
        Number valueSelling = (Number) jFormattedTextField2.getValue();

        if (jTextField3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a supplier ", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (jTextField4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a product ", "Warning", JOptionPane.WARNING_MESSAGE);

        } else if (valueBuying == null || valueBuying.doubleValue() == 0.0) {
            JOptionPane.showMessageDialog(this, "Please type buying price ", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!buyingPrice.matches("^(0|[1-9]\\d*)?(\\.\\d+)?(?<=\\d)$")) {
            JOptionPane.showMessageDialog(this, "Please type a valid buying price ", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (valueSelling == null || valueSelling.doubleValue() == 0.0) {
            JOptionPane.showMessageDialog(this, "Please type selling price ", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!sellingPrice.matches("^(0|[1-9]\\d*)?(\\.\\d+)?(?<=\\d)$")) {
            JOptionPane.showMessageDialog(this, "Please type a valid selling price ", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (Double.parseDouble(sellingPrice) < Double.parseDouble(jLabel21.getText())) {
            JOptionPane.showMessageDialog(this, "Selling price should be greater than rs." + jLabel21.getText(), "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (jTextField7.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please type quantity ", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (!jTextField7.getText().matches("^[1-9]\\d*$")) {
            JOptionPane.showMessageDialog(this, "Invalid Quantity ", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (jRadioButton1.isSelected()) {
            if (jTextField8.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please add Discount", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (!jTextField8.getText().matches("^[1-9]\\d*$")) {
                JOptionPane.showMessageDialog(this, "Invalid Discount", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (Double.parseDouble(jTextField8.getText()) >= Double.parseDouble(jLabel20.getText().replace("%", "").trim())) {
                JOptionPane.showMessageDialog(this, "Please add a discount amount less than " + jLabel20.getText(), "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (jDateChooser1.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Please add Discount Start Date", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (jDateChooser2.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Please add Discount End Date", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (jDateChooser1.getDate().after(jDateChooser2.getDate())) {
                JOptionPane.showMessageDialog(this, "Discount Start Date must be before or equal to End Date", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {

                GrnItem grnitem = new GrnItem();

                grnitem.setBuyingPrice(Double.parseDouble(buyingPrice));
                grnitem.setSellingPrice(Double.parseDouble(sellingPrice));
                grnitem.setQty(Double.parseDouble(qty));
                grnitem.setCategory(jTextField6.getText());
                grnitem.setProductID(jTextField4.getText());
                grnitem.setProductName(jTextField5.getText());

                grnitem.setDiscount(Double.parseDouble(jTextField8.getText()));
                grnitem.setDiscountStart(new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate()));
                grnitem.setDiscountEnd(new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser2.getDate()));

                if (grnItemMap.get(jTextField4.getText()) == null) {
                    grnItemMap.put(jTextField4.getText(), grnitem);
                    loadGrnItem();

                } else {
                    GrnItem found = grnItemMap.get(jTextField4.getText());

                    if (found.getBuyingPrice() == Double.parseDouble(buyingPrice)
                            && found.getSellingPrice() == Double.parseDouble(sellingPrice) && found.getDiscount() == Double.parseDouble(jTextField8.getText())) {

                        found.setQty(found.getQty() + Double.parseDouble(qty));
                        loadGrnItem();

                    } else {
                        //  grnItemMap.put(uniqueKey, grnitem);
                        //  loadGrnItem();
                        //  clearAll();

                        JOptionPane.showMessageDialog(this, "GRN item already exists with diffrent dates and prices", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        } else {

            GrnItem grnitem = new GrnItem();

            grnitem.setBuyingPrice(Double.parseDouble(buyingPrice));
            grnitem.setSellingPrice(Double.parseDouble(sellingPrice));
            grnitem.setQty(Double.parseDouble(qty));
            grnitem.setCategory(jTextField6.getText());
            grnitem.setProductID(jTextField4.getText());
            grnitem.setProductName(jTextField5.getText());

            grnitem.setDiscount(0.0);
            grnitem.setDiscountStart(null);
            grnitem.setDiscountEnd(null);

            if (grnItemMap.get(jTextField4.getText()) == null) {
                grnItemMap.put(jTextField4.getText(), grnitem);
                loadGrnItem();

            } else {
                GrnItem found = grnItemMap.get(jTextField4.getText());

                if (found.getBuyingPrice() == Double.parseDouble(buyingPrice)
                        && found.getSellingPrice() == Double.parseDouble(sellingPrice) && found.getDiscount() == Double.parseDouble(jTextField8.getText())) {

                    found.setQty(found.getQty() + Double.parseDouble(qty));
                    loadGrnItem();

                } else {
                    //  grnItemMap.put(uniqueKey, grnitem);
                    //  loadGrnItem();
                    //  clearAll();

                    JOptionPane.showMessageDialog(this, "GRN item already exists with diffrent dates and prices", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jTextField8.setText("");
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged

    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked

    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jTextField8.setText("0.0");
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            int row = jTable1.getSelectedRow();

            String removeGrnId = String.valueOf(jTable1.getValueAt(row, 0));
            if (grnItemMap.containsKey(removeGrnId)) {
                grnItemMap.remove(removeGrnId);
                loadGrnItem();
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            String grnNumber = jTextField2.getText();
            String supplierMobile = jTextField3.getText();
            String employeeEmail = jTextField1.getText();
            String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
            String paidAmount = jFormattedTextField3.getText();

            if (grnItemMap.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please add GRN items", "Warning", JOptionPane.WARNING_MESSAGE);

            }else if(jFormattedTextField4.getText().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Please add Payment", "Warning", JOptionPane.WARNING_MESSAGE);
            }else {

                logger.log(Level.INFO, "NewGRN Record Added:{0}", grnNumber);

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

                MySQL2.executeIUD("INSERT INTO `grn` VALUES('" + grnNumber + "','" + date + "',"
                        + "'" + paidAmount + "','" + supplierMobile + "','" + employeeEmail + "') ");

                for (GrnItem grnItem : grnItemMap.values()) {

                    ResultSet resultSet = MySQL2.executeSearch("SELECT * FROM `stock` WHERE"
                            + "`product_id`='" + grnItem.getProductID() + "' AND"
                            + "`price`='" + grnItem.getSellingPrice() + "'  AND `discount`='" + grnItem.getDiscount() + "' ");

                    String sid = "";
                    if (resultSet.next()) {
                        //existing stock

                        sid = resultSet.getString("id");

                        String currentQTY = resultSet.getString("qty");
                        String updateQuantity = String.valueOf(Double.parseDouble(currentQTY) + grnItem.getQty());
                        MySQL2.executeIUD("UPDATE `stock` SET `qty`='" + updateQuantity + "' WHERE `id`='" + sid + "' ");

                    } else {
                        //new stock

                        MySQL2.executeIUD("INSERT INTO `stock` (`price`,`qty`,`product_id`,`date`,`discount`,`discount_start`,`discount_end`)"
                                + "VALUES('" + grnItem.getSellingPrice() + "','" + grnItem.getQty() + "',"
                                + "'" + grnItem.getProductID() + "','" + date + "','" + grnItem.getDiscount() + "','" + grnItem.getDiscountStart() + "','" + grnItem.getDiscountEnd() + "') ");

                        ResultSet resultSet2 = MySQL2.executeSearch("SELECT * FROM `stock` WHERE"
                                + "`product_id`='" + grnItem.getProductID() + "' AND"
                                + "`price`='" + grnItem.getSellingPrice() + "' AND `date`='" + date + "' AND `discount`='" + grnItem.getDiscount() + "' AND `discount_start`='" + grnItem.getDiscountStart() + "' AND `discount_end`='" + grnItem.getDiscountEnd() + "' ");

                        if (resultSet2.next()) {
                            sid = resultSet2.getString("id");
                        }

                    }

                    // insert grn item
                    MySQL2.executeIUD("INSERT INTO `grn_item` (`qty`,`price`,`stock_id`,`grn_id`) "
                            + "VALUES ('" + grnItem.getQty() + "','" + grnItem.getBuyingPrice() + "','" + sid + "','" + grnNumber + "') ");

                }

                //  InputStream s = this.getClass().getResourceAsStream("/reports/grnreport.jasper");
                String s = "src//reports//grnreport.jasper";

                HashMap<String, Object> params = new HashMap<>();

                params.put("Parameter1", jTextField2.getText());
                params.put("Parameter2", jTextField1.getText());
                params.put("Parameter3", date);
                params.put("Parameter4", jFormattedTextField3.getText());
                params.put("Parameter7", jFormattedTextField4.getText());
                params.put("Parameter8", jFormattedTextField5.getText());
                params.put("Parameter9", jTextField3.getText());

                JRTableModelDataSource datasource = new JRTableModelDataSource(jTable1.getModel());

                JasperPrint jasperprint = JasperFillManager.fillReport(s, params, datasource);

                 JasperViewer.viewReport(jasperprint,false);
                
                grnItemMap.clear();
                loadGrnItem();
                clearAll();
            }

        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error in New GRN Record saving", e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jFormattedTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField4KeyReleased
        String total = jFormattedTextField3.getText();
        String payment = jFormattedTextField4.getText();
        //   Number valuePayment = (Number) jFormattedTextField4.getValue();
        if (payment.isEmpty()) {
            payment = "0";

        } else if (!payment.matches("^(0|[1-9]\\d*)?(\\.\\d+)?(?<=\\d)$")) {
            jFormattedTextField4.setText("INVALID");
            jFormattedTextField4.setForeground(Color.RED);
        } else {

            Double balance = Double.parseDouble(payment) - Double.parseDouble(total);
            if (balance < 0) {
                jButton5.setEnabled(false);
            } else {
                jButton5.setEnabled(true);
            }
            jFormattedTextField5.setText(String.valueOf(balance));
            jFormattedTextField5.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_jFormattedTextField4KeyReleased
    private ViewGrnHistory vgh;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (vgh == null || !vgh.isDisplayable()) {
            vgh = new ViewGrnHistory();
            vgh.setVisible(true);
        } else {

            vgh.requestFocus();
            vgh.toFront();
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clearAll();
    }//GEN-LAST:event_jButton4ActionPerformed
    private void clearAll() {

        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextArea1.setText("");
        jLabel20.setText("");
        jLabel21.setText("");
        jFormattedTextField1.setText("");
        jFormattedTextField2.setText("");
        jFormattedTextField3.setText("");
        jFormattedTextField4.setText("");
        jFormattedTextField5.setText("");
        jTextField2.setText(generateGrnID());
        jRadioButton2.setSelected(true);

        jTextField8.setText("0.0");
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        //grnItemMap.clear();
        // loadGrnItem();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
