/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Anne
 */
public class ProfileImgView extends javax.swing.JDialog {

    /**
     * Creates new form ProfileImgView
     */
    public ProfileImgView(java.awt.Frame parent, boolean modal,String path) {
        super(parent, modal);
        initComponents();
        
        int lblWidth = jLabel1.getWidth();
        int lblHeight = jLabel1.getHeight();
        
        ImageIcon orgIcon = new ImageIcon(path);
        Image orgImage = orgIcon.getImage();
        
        int imgWidth = orgIcon.getIconWidth();
        int imgheight = orgIcon.getIconHeight();
        
        double aspectRatio = (double) imgWidth/imgheight;
        
        int newWidth = lblWidth;
        int newHeight = (int) (lblWidth/aspectRatio);
        
         if (newHeight > lblHeight) {
        newHeight = lblHeight;
        newWidth = (int) (lblHeight * aspectRatio);
        
         }
         
         Image scaledImg = orgImage.getScaledInstance(newWidth, newHeight,Image.SCALE_SMOOTH);
         
         jLabel1.setIcon(new ImageIcon(scaledImg));

        
  
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Profile Image View");

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
