/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Panel.java to edit this template
 */
package gui;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.BorderLayout;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Anne
 */
public class SubHomeA extends javax.swing.JPanel {
 static final Logger logger = SignIn.getLoggerObject();
      public SubHomeA() {
         try {

            UIManager.setLookAndFeel(new FlatMacDarkLaf());

        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        SwingUtilities.updateComponentTreeUI(this);
        this.revalidate();
        this.repaint();

        initComponents();
          initializeCurrentPage();
    }
    
     
    private void initializeCurrentPage() {
        logger.info("Supplier Managment Dashboard accessed");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CompanyRegistration = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        CompanyRegistration.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CompanyRegistration.setForeground(new java.awt.Color(153, 153, 255));
        CompanyRegistration.setText("Company Registration");
        CompanyRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyRegistrationActionPerformed(evt);
            }
        });
        jPanel1.add(CompanyRegistration);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Supplier Registration");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void CompanyRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyRegistrationActionPerformed
    jPanel1.setVisible(false); 
    jPanel1.removeAll();       

    CompanyRegistration cr = new CompanyRegistration(jPanel1);
    jPanel1.add(cr, BorderLayout.CENTER); 

    jPanel1.setBorder(null);   

    jPanel1.revalidate();       
    jPanel1.repaint();          
    jPanel1.setVisible(true);
    }//GEN-LAST:event_CompanyRegistrationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    jPanel1.setVisible(false); 
    jPanel1.removeAll();       

    SupplierRegistration sr = new SupplierRegistration(jPanel1);
    jPanel1.add(sr, BorderLayout.CENTER); 

    jPanel1.setBorder(null);   

    jPanel1.revalidate();       
    jPanel1.repaint();          
    jPanel1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompanyRegistration;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
